version: "3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ares
    ports:
    - 5432:5432